services:

  api-gateway:
    depends_on:
      - discovery-server
    build:
      context: ../
      dockerfile: ./Dockerfile-api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - localnet

  discovery-server:
    depends_on:
      - tempo
      - grafana
    build:
      context: ../
      dockerfile: ./Dockerfile-discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - localnet

  cfg-first-k-service:
    depends_on:
      - discovery-server
    build:
      context: ../
      dockerfile: ./Dockerfile-cfg-first-k-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
    networks:
      - localnet

  tempo:
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./tempo/tempo-data:/tmp/tempo
#    ports:
    #      - "3110:3100"  # Tempo
#      - "9411:9411" # zipkin
    networks:
      - localnet

  grafana:
    image: grafana/grafana:10.1.0
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - localnet

  loki:
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    networks:
      - localnet

networks:
  localnet: