services:
  cfg-examples-db:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: Dockerfile-cfg-examples-db
    networks:
      - examples-net

  cfg-examples:
    restart: unless-stopped
    depends_on:
      - cfg-examples-db
    build:
      context: ../
      dockerfile: Dockerfile-cfg-examples
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - localnet
      - examples-net

  api-gateway:
    restart: unless-stopped
    depends_on:
      - discovery-server
    build:
      context: ../
      dockerfile: Dockerfile-api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - localnet

  discovery-server:
    restart: unless-stopped
    depends_on:
      - tempo
      - grafana
    build:
      context: ../
      dockerfile: Dockerfile-discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - localnet

  cfg-processor:
    restart: unless-stopped
    depends_on:
      - discovery-server
    build:
      context: ../
      dockerfile: Dockerfile-cfg-processor
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
    networks:
      - localnet

  tempo:
    restart: unless-stopped
    image: grafana/tempo:2.4.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./tempo/tempo-data:/tmp/tempo
#    ports:
    #      - "3110:3100"  # Tempo
#      - "9411:9411" # zipkin
    networks:
      - localnet

  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.3.5
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      - localnet

  loki:
    restart: unless-stopped
    image: grafana/loki:2.8.11
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    networks:
      - localnet

networks:
  localnet:
  examples-net: