bsu:
  cfg-first-k-service:
    name: cfg-first-k-service
  discovery-server:
    uri: http://localhost:8761

eureka:
  client:
    serviceUrl:
      defaultZone: ${bsu.discovery-server.uri}/eureka

server:
  port: 8080

spring:
  application:
    name: api-gateway

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud.gateway: TRACE
        cloud.gateway.route:
          RouteDefinitionLocator: INFO