eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring:application:instance_id:${random:value}}

server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/product-service
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
